In [1]:
import numpy as np

In [2]:
lista = [2, 3, 4]
np.array(lista)


array([2, 3, 4])

In [3]:
np.array(range(3, 6))

array([3, 4, 5])

In [4]:
np.arange(3, 6)

array([3, 4, 5])

In [5]:
array = np.arange(3, 16, 2)
array

array([ 3,  5,  7,  9, 11, 13, 15])

In [6]:
lista = [ 3,  5,  7,  9, 11, 13, 15]
list(map(lambda x: x+2, lista))

[5, 7, 9, 11, 13, 15, 17]

In [7]:
array = np.array([ 3,  5,  7,  9, 11, 13, 15]) 
array

array([ 3,  5,  7,  9, 11, 13, 15])

In [8]:
array + 2

array([ 5,  7,  9, 11, 13, 15, 17])

In [9]:
array * 2

array([ 6, 10, 14, 18, 22, 26, 30])

In [10]:
array ** 2

array([  9,  25,  49,  81, 121, 169, 225])

In [11]:
lista = [ 3,  5,  7,  9, 11, 13, 15]
lista + lista

[3, 5, 7, 9, 11, 13, 15, 3, 5, 7, 9, 11, 13, 15]

In [12]:
array = np.array([ 3,  5,  7,  9, 11, 13, 15]) 
array + array

array([ 6, 10, 14, 18, 22, 26, 30])

In [15]:
array = np.array([ 3,  5,  7,  9, 11, 13, 15]) 
array.shape, type(array.shape)

((7,), tuple)

In [17]:
array = np.array([ [3,  5,  7,  9], [11, 13, 15, 17]]) 
array.shape, array

((2, 4),
 array([[ 3,  5,  7,  9],
        [11, 13, 15, 17]]))

In [19]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
array > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [21]:
array[array > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
np.random.randint(1, 10)

7

In [25]:
np.random.randint(1, 10, 3)

array([8, 3, 5])

In [26]:
np.random.randint(1, 10, 3)

array([3, 6, 2])

In [27]:
np.random.random()

0.22365128308131366

In [28]:
np.random.random(5)

array([0.94587679, 0.95978359, 0.00154759, 0.88668437, 0.18048048])