In [1]:
import numpy as np

In [2]:
np.array([2, 3, 4, 5])

array([2, 3, 4, 5])

In [3]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
array = np.arange(10, 20)
array, array.size, array.min(), array.max()

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 10,
 np.int64(10),
 np.int64(19))

In [5]:
array = np.random.randint(1, 100, 10)
array

array([92, 10, 14, 75, 87, 14, 63,  6, 28, 21])

In [6]:
array > 50

array([ True, False, False,  True,  True, False,  True, False, False,
       False])

In [9]:
array[array < 50]

array([10, 14, 14,  6, 28, 21])

In [12]:
array[(array < 50) & (array > 10)]

array([14, 14, 28, 21])

In [13]:
array[(array > 50) | (array < 10)]

array([92, 75, 87, 63,  6])

In [14]:
array = np.random.randint(1, 100, 10) 
array

array([13, 39, 90, 10, 86, 70, 53,  4, 26, 91])

In [15]:
array * 2

array([ 26,  78, 180,  20, 172, 140, 106,   8,  52, 182])

In [16]:
array[:4]

array([13, 39, 90, 10])

In [17]:
array = np.random.randint(1, 100, (3, 3)) 
array

array([[60, 21, 34],
       [72,  1, 28],
       [81, 46, 93]])

In [18]:
array[1]

array([72,  1, 28])

In [20]:
array[1][2]

np.int64(28)

In [21]:
array[1, 2]

np.int64(28)

# Exercitiul an bisect